import type { PortfolioTemplate, PortfolioData } from "../../src/portfolio-templates.js";
import { esc, buildLinks, sectionWrapper } from "../../src/portfolio-templates.js";

export const minimalTemplate: PortfolioTemplate = {
  name: "minimal",
  description: "System-ui, monochrome ink-on-paper, generous whitespace, no decoration, light/dark",

  render(data: PortfolioData): { html: string; populated: string[]; placeholders: string[] } {
    const { profile, repos, maxRepos } = data;
    const id = profile.identity ?? {};
    const populated: string[] = [];
    const placeholders: string[] = [];

    const links = buildLinks(id);

    const skills = profile.skills ?? [];
    const skillsBody = skills
      .map(
        (c) =>
          `<div class="skill-group"><h3>${esc(c.category)}</h3><p>${c.skills.map((s) => esc(s)).join(", ")}</p></div>`
      )
      .join("");

    const experience = profile.experience ?? [];
    const expBody = experience
      .map(
        (e) =>
          `<article><h3>${esc(e.title ?? "")} \u2014 ${esc(e.company ?? "")}</h3><p class="meta">${esc(e.startDate ?? "")}${e.endDate ? ` \u2013 ${esc(e.endDate)}` : " \u2013 present"}</p>${(e.responsibilities ?? []).slice(0, 4).map((r) => `<p>${esc(r)}</p>`).join("")}</article>`
      )
      .join("");

    const education = profile.education ?? [];
    const eduBody = education
      .map((e) => `<article><h3>${esc(e.institution ?? "")}</h3><p>${esc(e.degree ?? "")}</p></article>`)
      .join("");

    const repoBody = repos
      .slice(0, maxRepos)
      .map((r) => {
        const url = r.html_url ?? r.url ?? "";
        const name = r.name ?? "unnamed";
        return `<article><h3>${url ? `<a href="${esc(url)}">${esc(name)}</a>` : esc(name)}</h3><p>${esc(r.description ?? "")}</p>${r.language ? `<p class="meta">${esc(r.language)}</p>` : ""}</article>`;
      })
      .join("");

    const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(id.name ?? "Portfolio")}</title>
<style>
:root {
  --ink: #1a1a1a;
  --muted: #666;
  --line: #ddd;
  --bg: #fff;
}
@media (prefers-color-scheme: dark) {
  :root {
    --ink: #e0e0e0;
    --muted: #999;
    --line: #333;
    --bg: #0f0f0f;
  }
}
* { box-sizing: border-box; margin: 0; }
body {
  font: 16px/1.7 -apple-system, system-ui, sans-serif;
  color: var(--ink);
  background: var(--bg);
  max-width: 720px;
  margin: 0 auto;
  padding: 3rem 1.5rem;
}
header { margin-bottom: 3rem; }
h1 { font-size: 1.6rem; font-weight: 600; margin-bottom: 0.3rem; }
.headline { color: var(--muted); font-size: 1rem; margin-bottom: 0.75rem; }
nav a { color: var(--ink); margin-right: 1.25rem; text-decoration: underline; text-decoration-color: var(--line); font-size: 0.9rem; }
nav a:hover { text-decoration-color: var(--ink); }

section { margin-top: 2.5rem; }
h2 { font-size: 0.8rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.1em; color: var(--muted); margin-bottom: 1rem; }

article { margin-bottom: 1.25rem; }
article h3 { font-size: 1.05rem; font-weight: 600; }
article a { color: var(--ink); text-decoration: underline; }
article p { margin-top: 0.35rem; }
p.meta { color: var(--muted); font-size: 0.85rem; }

.skill-group { margin-bottom: 0.8rem; }
.skill-group h3 { font-size: 0.9rem; font-weight: 500; color: var(--muted); margin-bottom: 0.2rem; }
.skill-group p { font-size: 0.92rem; }

p.placeholder { color: var(--muted); font-style: italic; font-size: 0.9rem; }
footer { margin-top: 4rem; color: var(--muted); font-size: 0.75rem; }
</style>
</head>
<body>
<header>
  <h1>${esc(id.name ?? "Your Name")}</h1>
  ${id.headline ? `<p class="headline">${esc(id.headline)}</p>` : ""}
  <nav>${links.map((l) => `<a href="${esc(l.href)}">${esc(l.label)}</a>`).join("")}</nav>
</header>
${sectionWrapper("Skills", skills.length > 0, skillsBody, "No skills recorded yet \u2014 run: bun run profile", populated, placeholders)}
${sectionWrapper("Experience", experience.length > 0, expBody, "No experience recorded yet", populated, placeholders)}
${sectionWrapper("Education", education.length > 0, eduBody, "No education recorded yet", populated, placeholders)}
${sectionWrapper("Open Source & Projects", repos.length > 0, repoBody, "No GitHub data staged \u2014 run: bun run profile:github", populated, placeholders)}
<footer>Generated by ai-job-search portfolio generator \u2014 content sourced only from the candidate profile; empty sections stay honest.</footer>
</body>
</html>`;

    return { html, populated, placeholders };
  },
};
